import { BehaviorSubject } from 'rxjs';

export const routes = {


  layoutDirection: undefined,
  Url: '',
  rtl: undefined,
  adminDashboard: undefined,

  // Authentication
  login: '/auth/login',
  forgot_password: '/auth/forgot-password',
  register: '/auth/register',
  emailVerification: '/auth/email-verification',
  twoStepVerification: '/auth/two-step-verification',
  resetPassword: '/auth/reset-password',
  success: '/auth/success',
  lock_screen: '/auth/lock-screen',
  index: '/index',
  AdminDashboard2: '/admin-dashboard',
  notifications:'/notifications',
  // Customer Module
  customerDashboard: '/customer/dashboard',
  customerQuotations: '/customer/quotations',
  customeraddQuotations: '/customer/add-quotations',
  customereditQuotations: '/customer/edit-quotations',
  customerInvoices: '/customer/invoices',
  customerRecurringInvoices: '/customer/recurring-invoices',
  customerTransactions: '/customer/transactions',
  customerPaymentSummary: '/customer/payment-summary',
  customerInvoicereport: '/customer/invoice-report',
  customerSettings: '/customer/settings',
  customerAccountsettings: '/customer/settings/account-settings',
  customerSecuritysettings: '/customer/settings/security-settings',
  customerPlanssettings: '/customer/settings/plans-billing',
  customerNotificationsettings: '/customer/settings/notification-settings',
  customerInvoiceDetails: '/customer/invoice-details',
  activecustomer: '/customer/active-customers',
  deactivecustomer: '/customer/deactive-customers',


  // UI Components
  baseUi: '/base-ui',
  blankPage: '/blank-page',
  alert: '/base-ui/alert',
  accordions: '/base-ui/accordions',
  avatar: '/base-ui/avatar',
  badges: '/base-ui/badges',
  buttons: '/base-ui/buttons',
  buttonGroup: '/base-ui/button-group',
  breadcrumb: '/base-ui/breadcrumb',
  cards: '/base-ui/cards',
  carousel: '/base-ui/carousel',
  collapse: '/base-ui/collapse',
  dropDown: '/base-ui/drop-down',
  ratio: '/base-ui/ratio',
  links: '/base-ui/links',
  listGroup: '/base-ui/list-group',
  grid: '/base-ui/grid',
  images: '/base-ui/images',
  lightBox: '/advanced-ui/light-box',
  modal: '/base-ui/modal',
  offcanvas: '/base-ui/offcanvas',
  pagination: '/base-ui/pagination',
  placeholder: '/base-ui/placeholder',
  popover: '/base-ui/popover',
  progressBars: '/base-ui/progress-bars',
  rangeSlider: '/advanced-ui/range-slider',
  spinner: '/base-ui/spinner',
  tabs: '/base-ui/tabs',
  sweetAlert: '/base-ui/sweet-alerts',
  toasts: '/base-ui/toasts',
  tooltip: '/base-ui/tooltip',
  typography: '/base-ui/typography',
  utilities: '/base-ui/utilities',
  advancedUi: '/advanced-ui',
  ribbon: '/advanced-ui/ribbon',
  clipboards: '/advanced-ui/clipboards',
  dragDrop: '/advanced-ui/drag-drop',
  rating: '/advanced-ui/rating',
  textEditor: '/advanced-ui/text-editor',
  counter: '/advanced-ui/counter',
  scrollbar: '/advanced-ui/scrollbar',
  table: '/tables',
  basicTable: '/tables/basic',
  dataTable: '/tables/data-table',
  icon: '/icon',
  fontawesome: '/icon/fontawesome',
  leaftlet: '/maps/leaflets',
  feather: '/icon/feather',
  ionic: '/icon/ionic',
  material: '/icon/material',
  pe7: '/icon/pe7',
  themify: '/icon/themify',
  typicon: '/icon/typicon',
  weather: '/icon/weather',
  simpleLine: '/icon/simple-line',
  flag: '/icon/flag',
  forms: '/forms',
  basicForm: '/forms/basic-inputs',
  checkboxRadios: '/forms/form-checkbox-radios',
  gridGutters: '/forms/form-grid-gutters',
  horizontalForm: '/forms/horizontal-form',
  verticalForm: '/forms/vertical-form',
  formMask: '/forms/form-mask',
  formValidation: '/forms/form-validation',
  inputGroups: '/forms/input-groups',
  fileUpload: '/forms/file-upload',
  chart: '/chart',
  apexChart: '/chart/apex-charts',
  ngTwoCharts: '/chart/ng2-charts',
  primeng: '/chart/prime-ng',
  googleMaps: '/google-maps',
  //Application
  chat: '/application/chat',
  calender: '/application/calender',
  email: '/application/email',
  emailReply: '/application/email-reply',
  todo: '/application/todo',
  todoList: '/application/todo-list',
  notes: '/application/notes',
  socialFeed: '/application/social-feed',
  fileManager: '/application/file-manager',
  kanbanView: '/application/kanban-view',
  contacts: '/application/contacts',
  applicationInvoice: '/application/invoice',
  searchList: '/application/search-list',
  voiceCall: '/application/calls/voice-call',
  videoCall: '/application/calls/video-call',
  outgoingCall: '/application/calls/outgoing-call',
  incomingCall: '/application/calls/incoming-call',
  callHistory: '/application/calls/call-history',
  //Finance and Accounts
  expenses: '/expense',
  incomes: '/incomes',
  payments: '/payments',
  transactions: '/transactions',
  bankAccounts: '/bank-accounts',
  bankAccountList: '/bank-accounts/bank-accounts-list',
  bankAccountsType: '/bank-accounts/bank-accounts-type',
  moneyTransfer: '/money-transfer',
  //Manage
  manageUsers: '/manage-users',
  users: '/manage-users/users',
  rolesPermissions: '/manage-users/roles-permissions',
  permission: '/manage-users/permission',
  deleteAccountRequest: '/manage-users/delete-account-request',
  //Membership
  membership: '/membership',
  membershipPlans: '/membership/membership-plans',
  membershipAddons: '/membership/membership-addons',
  subscribers: '/membership/subscribers',
  membershipTransactions: '/membership/membership-transactions',
  contactMessages: '/contact-messages',
  tickets: '/tickets',
  ticketList: '/tickets/ticket-list',
  ticketLists: '/tickets/ticket-lists',
  ticketKanban: '/tickets/ticket-kanban',
  ticketDetails: '/tickets/ticket-details',

  items: '/items',
  invoiceItems: '/items/invoice-items',
  allInventory: '/inventory',
  invoiceItemList: '/items/invoice-list',
  invoiceItemCategory: '/items/invoice-category',

  invoice: '/invoices',
  invoiceList: '/invoices/invoice-list',
  invoiceTemplate: '/invoices/invoice-templates',
  addInvoice: '/invoices/add-invoice',
  editInvoice: '/invoices/edit-invoice',
  invoiceDetails: '/invoices/invoice-details',
  recurringInvoices: '/invoices/recurring-invoices',

   // Credit Notes
   creditNote: '/credit-notes',
   creditNotes: '/credit-notes/credit-note-list',
   addCreditNotes: '/credit-notes/add-credit-notes',
   editCreditNotes: '/credit-notes/edit-credit-notes',
 
   // Quotations
   quotations: '/quotations',
   quotationList: '/quotations/quotation-list',
   addQuotations: '/quotations/add-quotation',
   editQuotations: '/quotations/edit-quotation',
 
   // Delivery Challans
   deliveryChallan: '/delivery-challans',
   deliveryChallanList: '/delivery-challans/delivery-challan-list',
   addDeliveryChallan: '/delivery-challans/add-delivery-challan',
   editDeliveryChallan: '/delivery-challans/edit-delivery-challan',


   // Customers
  customers: '/customers',
  customerList: '/customers/customer-list',
  customerDetails: '/customers/customer-details',
  addCustomer: '/customers/add-customer',
  editCustomer: '/customers/edit-customer',

  // Purchases
  purchases: '/purchases',
  purchaseList: '/purchases/purchase-list',
  addPurchase: '/purchases/add-purchase',
  editPurchase: '/purchases/edit-purchase',

  // Purchase Orders
  purchaseOrder: '/purchase-orders',
  purchaseOrderList: '/purchase-orders/purchases-order-list',
  addPurchaseOrder: '/purchase-orders/add-purchases-orders',
  editPurchaseOrder: '/purchase-orders/edit-purchases-orders',

    // Debit Notes
    debitNotes: '/debit-notes',
    debitNoteList: '/debit-notes/debit-note-list',
    addDebitNotes: '/debit-notes/add-debit-notes',
    editDebitNotes: '/debit-notes/edit-debit-notes',

    suppliers: '/suppliers',
    supplierPayments: '/supplier-payments',
  //Report
  stockSummary: '/reports/item-report/stock-summary',
  inventoryReport: '/reports/item-report/inventory-report',
  bestSeller: '/reports/item-report/best-seller',
  lowStock: '/reports/item-report/low-stock',
  stockHistory: '/reports/item-report/stock-history',
  soldStock: '/reports/item-report/sold-stock',
  expenseReport: '/reports/accounting-report/expense-report',
  incomeReport: '/reports/accounting-report/income-report',
  profitlossReport: '/reports/accounting-report/profit-loss-report',
  annualReport: '/reports/accounting-report/annual-report',
  balanceSheet: '/reports/accounting-report/balance-sheet',
  trialBalance: '/reports/accounting-report/trial-balance',
  cashFlow: '/reports/accounting-report/cash-flow',
  accountStatement: '/reports/accounting-report/account-statement',
  paymentSummary: '/reports/finance-reports/payment-summary',
  taxReport: '/reports/finance-reports/tax-report',
  customerReport: '/reports/user-reports/customers-report',
  customerDueReport: '/reports/user-reports/customer-due-reports',
  supplierReport: '/reports/user-reports/supplier-reports',
  salesReport: '/reports/transaction-report/sales-report',
  salesReturns: '/reports/transaction-report/sales-returns',
  salesOrders: '/reports/transaction-report/sales-orders',
  purchasesReport: '/reports/transaction-report/purchases-report',
  purchasesReturnReport: '/reports/transaction-report/purchase-return-report',
  purchasesOrdersReport: '/reports/transaction-report/purchase-orders-reports',
  quotationReport: '/reports/transaction-report/quotation-report',
  //Setting NEW
  accountSettings: '/settings/general-settings/account-settings',
  securitySettings: '/settings/general-settings/security-settings',
  plansBillings: '/settings/general-settings/plans-billings',
  notificationSettings: '/settings/general-settings/notifications-settings',
  integrationsSettings: '/settings/general-settings/integrations-settings',

  companySettings: '/settings/website-settings/company-settings',
  localizationSettings: '/settings/website-settings/localization-settings',
  prefixesSettings: '/settings/website-settings/prefixes-settings',
  preferenceSettings: '/settings/website-settings/preference-settings',
  seoSetup: '/settings/website-settings/seo-setup',
  languageSettings: '/settings/website-settings/language-settings',
  languageSettings2: '/settings/website-settings/language-settings2',
  maintenanceMode: '/settings/website-settings/maintenance-mode',
  authenticationSettings: '/settings/website-settings/authentication-settings',
  aiConfigurationSettings: '/settings/website-settings/ai-configuration-settings',
  appearanceSettings: '/settings/website-settings/appearance-settings',
  pluginManager: '/settings/website-settings/plugin-manager',

  invoiceSettings: '/settings/app-settings/invoice-settings',
  invoiceTemplates: '/settings/app-settings/invoice-templates',
  esignatures: '/settings/app-settings/esignatures',
  barcodeSettings: '/settings/app-settings/barcode-settings',
  thermalPrinter: '/settings/app-settings/thermal-printer',
  customFields: '/settings/app-settings/custom-fields',
  saasSettings: '/settings/app-settings/saas-settings',

  paymentMethods: '/settings/finance-settings/payment-methods',
  bankAccountsSettings: '/settings/finance-settings/bank-accounts-settings',
  taxRates: '/settings/finance-settings/tax-rates',
  currencies: '/settings/finance-settings/currencies',

  emailSettings: '/settings/system-settings/email-settings',
  emailTemplates: '/settings/system-settings/email-templates',
  smsGateways: '/settings/system-settings/sms-gateways',
  gdprCookies: '/settings/system-settings/gdpr-cookies',
  
  customCss: '/settings/other-settings/custom-css',
  customJs: '/settings/other-settings/custom-js',
  sitemap: '/settings/other-settings/sitemap',
  clearCache: '/settings/other-settings/clear-cache',
  storage: '/settings/other-settings/storage',
  cronjob: '/settings/other-settings/cronjob',
  systemBackup: '/settings/other-settings/system-backup',
  databaseBackup: '/settings/other-settings/database-backup',
  systemUpdate: '/settings/other-settings/system-update',
  //Content
  pages: '/pages',
  blogs: '/blogs',
  addBlogs: '/blogs/add-blogs',
  editblogs: '/blogs/edit-blogs',
  allBlogs: '/blogs/all-blogs',
  blogcomments: '/blogs/blog-comments',
  blogtag: '/blogs/blog-tags',
  blogCategories: '/blogs/blog-categories',
  blogDetails: '/blogs/blog-details',
  countries: '/location/countries',
  states: '/location/states',
  cities: '/location/cities',
  testimonials: '/testimonials',
  faq: '/faq',
  //Pages
  profile: '/profile',
  starter: '/starter',
  gallery: '/gallery',
  pricing: '/pricing',
  timelines: '/timeline',
  apiKeys: '/api-keys',
  privacyPolicy: '/privacy-policy',
  termsCondition: '/terms-condition',
  comingSoon: '/coming-soon',
  underMaintenance: '/under-maintenance',
  underConstruction: '/under-construction',
  error404: '/error/error-404',
  error500: '/error/error-500',

  
  //New General Invoices 
  generalInvoice1: '/invoice-modals/general-invoice-1',
  generalInvoice2: '/invoice-modals/general-invoice-2',
  generalInvoice3: '/invoice-modals/general-invoice-3',
  generalInvoice4: '/invoice-modals/general-invoice-4',
  generalInvoice5: '/invoice-modals/general-invoice-5',
  generalInvoice6: '/invoice-modals/general-invoice-6',
  generalInvoice7: '/invoice-modals/general-invoice-7',
  generalInvoice8: '/invoice-modals/general-invoice-8',
  generalInvoice9: '/invoice-modals/general-invoice-9',
  generalInvoice10: '/invoice-modals/general-invoice-10',
  busBookingInvoice: '/invoice-modals/bus-booking-invoice',
  carBookingInvoice: '/invoice-modals/car-booking-invoice',
  coffeeShopInvoice: '/invoice-modals/coffee-shop-invoice',
  domainHostingInvoice: '/invoice-modals/domain-hosting-invoice',
  ecommerceInvoice: '/invoice-modals/ecommerce-invoice',
  fitnessCenterInvoice: '/invoice-modals/fitness-center-invoice',
  flightBookingInvoice: '/invoice-modals/flight-booking-invoice',
  hotelBookingInvoice: '/invoice-modals/hotel-booking-invoice',
  internetBillingInvoice: '/invoice-modals/internet-billing-invoice',
  invoiceMedical: '/invoice-modals/invoice-medical',
  moneyExchangeInvoice: '/invoice-modals/money-exchange-invoice',
  movieTicketBookingInvoice: '/invoice-modals/movie-ticket-booking-invoice',
  restaurantsInvoice: '/invoice-modals/restaurants-invoice',
  studentBillingInvoice: '/invoice-modals/student-billing-invoice',
  trainTicketInvoice: '/invoice-modals/train-ticket-invoice',
  receiptInvoice1: '/invoice-modals/receipt-invoice-1',
  receiptInvoice2: '/invoice-modals/receipt-invoice-2',
  receiptInvoice3: '/invoice-modals/receipt-invoice-3',
  receiptInvoice4: '/invoice-modals/receipt-invoice-4',
  //
  addProducts: '/product-service/add-products',
  editProducts: '/product-service/edit-products',
  productlist: '/product-service/product-list',
  category: '/product-service/category',
  units: '/product-service/units',
  addunits: '/product-service/add-units',
  editunits: '/product-service/edit-units',
  creditnotepage: '/credit-note-pages',
  creditnotes: '/creditnotepage/credit-notes',
  payonline: '/pay-online',
  mailpayinvoice: '/mail-pay-invoice',
  report: '/report',
  companies: '/super-admin/companies',
  subscriptions: '/super-admin/subscriptions',
  packages: '/super-admin/packages',
  packagesGrid: '/super-admin/packages-grid',
  domainRequest: '/super-admin/domain-request',
  domain: '/super-admin/domain',
  purchaseTransaction: '/super-admin/purchase-transaction',
  superAdminDashboard: '/super-admin/dashboard',
  plansList: '/super-admin/plans-list',
  formpickers: '/forms/form-pickers',
  planBilling: '/settings/plan-billing',
  twoFactor: '/settings/two-factor',
  customField: '/settings/custom-field',
  dataTables: '/tables/data-table',
  deliveryChallansList: '/delivery-challans/list',
  addDeliveryChallans: '/delivery-challans/add-delivery-challans',
  editDeliveryChallans: '/delivery-challans/edit-delivery-challans',
  emailTemplate: '/settings/email-template',
  seoSetting: '/settings/seo-settings',
  sassSetting: '/settings/sass-settings',
  //Layout Pages
  default: '/layout-default',
  single: '/layout-single',
  mini: '/layout-mini',
  transparent: '/layout-transparent',
  withoutHeader: '/layout-without-header',
  Boxed: '/layout-boxed',
  RTL: '/layout-rtl',
  Dark: '/layout-dark',



};

// Set up rtl subscription (if needed)
// routes.rtl = routes.layoutDirection.subscribe((res: string) => {
//   if (res == 'rtl') routes.Url = res;
// });


